export const gameList = [
  "Hogwarts Legacy",
  "Cyberpunk 2077",
  "Elden Ring",
  "Call of Duty: Warzone",
  "Red Dead Redemption 2",
  "Assassin's Creed Valhalla",
  "Far Cry 6",
  "Resident Evil Village",
  "Battlefield 2042",
  "Halo Infinite",
  "The Witcher 3: Wild Hunt",
  "GTA V",
  "Doom Eternal",
  "Control",
  "Metro Exodus",
  "Counter-Strike 2",
  "Valorant",
  "League of Legends",
  "Fortnite",
  "Minecraft",
  "PUBG",
  "Dota 2",
  "Overwatch 2",
  "Rainbow Six Siege",
  "FIFA 24",
  "NBA 2K24",
  "Lost Ark",
  "Rust",
  "ARK: Survival Evolved",
  "Escape from Tarkov",
  "Starfield",
  "Palworld",
  "Helldivers 2",
  "Genshin Impact",
  "Dark Souls III"
];