
export const gameList = [
  "Counter-Strike 2",
  "Valorant",
  "League of Legends",
  "Fortnite",
  "Call of Duty: Warzone",
  "GTA V",
  "Cyberpunk 2077",
  "Minecraft",
  "Apex Legends",
  "Elden Ring",
  "PUBG",
  "Dota 2",
  "Overwatch 2",
  "Rainbow Six Siege",
  "Hogwarts Legacy",
  "Red Dead Redemption 2",
  "Assassin's Creed Valhalla",
  "The Witcher 3",
  "Battlefield 2042",
  "FIFA 24",
  "NBA 2K24",
  "Lost Ark",
  "Rust",
  "ARK: Survival Evolved",
  "Escape from Tarkov",
  "Starfield",
  "Palworld",
  "Helldivers 2",
  "Genshin Impact",
  "Dark Souls III"
];
